---
title: "midterm"
subtitle: "MUSA508 // Midterm"
authors: Alex Cartwright & Max Masuda-Farkas
output:
  html_document:
    code_folding: hide
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(tidycensus)
library(sf)
library(spdep)
library(caret)
library(ckanr)
library(FNN)
library(grid)
library(gridExtra)
library(ggcorrplot)
library(kableExtra)

root.dir = "https://raw.githubusercontent.com/urbanSpatial/Public-Policy-Analytics-Landing/master/DATA/"
source("https://raw.githubusercontent.com/urbanSpatial/Public-Policy-Analytics-Landing/master/functions.r")
palette5 <- c("#25CB10", "#5AB60C", "#8FA108",   "#C48C04", "#FA7800")

options(scipen = 999)
```

```{r data pull, include = TRUE, message=FALSE, warning=FALSE}

# create boulder_homes geojson dataset, convert to sf, condition data
boulder_homes <- 
  st_read("studentData.geojson", crs = 'ESRI:102254') %>%
  mutate(price_per_sf = price / TotalFinishedSF) %>%
  mutate(Age = 2021 - builtYear)

boulder_homes$AcDscr = ifelse(is.na(boulder_homes$Ac) | 
                              boulder_homes$Ac == 200,
                              "No AC", boulder_homes$AcDscr)

# There are a dozen or so home records with 1 or 0 sq.ft. of finished area.
# These records are removed because they are not representative of the full data
boulder_homes <- boulder_homes %>%
  dplyr::filter(TotalFinishedSF > 1)

boulder_boundary <-
  st_read("County_Boundary.geojson") %>%
  st_transform('ESRI:102254')

var19 <- load_variables(2019, "acs5", cache = TRUE)

acs_vars <- c(
  "B19013_001E", # Med HH Income
  "B06010_001E", # total earners
  "B06010_011E", # number of earners making over $75K
  "C24070_001E", # Labor force
  "C24070_002E", # Agriculture, forestry, fishing and hunting, and mining
  "C24070_003E", # Construction
  "C24070_004E", # Manufacturing
  "C24070_005E", # Wholesale trade
  "C24070_006E", # Retail trade
  "C24070_007E", # Transportation and warehousing, and utilities
  "C24070_008E", # Information
  "C24070_009E", # Finance and insurance, and real estate, and rental and leasing
  "C24070_010E", # Professional, scientific, and management, and administrative, and waste management services
  "C24070_011E", # Educational services, and  health care and social assistance
  "C24070_012E") # Arts, entertainment, and recreation, and accommodation and food services

acsTractsBoulder.2019.sf <- get_acs(geography = "tract",
                                   year = 2019, 
                                   variables = acs_vars, 
                                   geometry = TRUE, 
                                   state = "CO", 
                                   county = "Boulder", 
                                   output = "wide") %>%
  st_transform('ESRI:102254')

acsTractsBoulder.2019.sf <- acsTractsBoulder.2019.sf %>%
  dplyr::select(GEOID, NAME, all_of(acs_vars)) %>%
  rename(med_HH_Income = B19013_001E,
         tot_earners = B06010_001E,
         over75K = B06010_011E,
         employed = C24070_001E,
         Ag_Mining = C24070_002E,
         Construction = C24070_003E,
         Manufacturing = C24070_004E,
         Wholesale = C24070_005E,
         Retail = C24070_006E,
         Transportation = C24070_007E,
         Information = C24070_008E,
         Finance = C24070_009E,
         Professional = C24070_010E,
         Ed_Health = C24070_011E,
         ArtsRecEnt = C24070_012E) %>%
  mutate(
         pct.over75K = over75K/tot_earners,
         pct.Ag_Mining = Ag_Mining/employed,
         pct.Construction = Construction/employed,
         pct.Manufacturing = Manufacturing/employed,
         pct.Wholesale = Wholesale/employed,
         pct.Retail = Retail/employed,
         pct.Transportation = Transportation/employed,
         pct.Information = Information/employed,
         pct.Finance = Finance/employed,
         pct.Professional = Professional/employed,
         pct.Ed_Health = Ed_Health/employed,
         pct.ArtsRecEnt = ArtsRecEnt/employed)

censusFactors <- acsTractsBoulder.2019.sf %>%
  select(med_HH_Income, pct.over75K, pct.Information, pct.Finance, pct.Professional,
         pct.Ed_Health)

# Join census data to boulder_homes

boulder_homes <-
  st_join(boulder_homes, censusFactors)

# Front Range polyline

FrontRange = st_read("FrontRange.shp") %>%
  st_transform('ESRI:102254')

boulder_homes <- boulder_homes %>%
  mutate(dist_FR = as.numeric(st_distance(., FrontRange)))

# Municipal Boundaries of Boulder County
munis <- st_read("https://opendata.arcgis.com/datasets/9597d3916aba47e887ca563d5ac15938_0.geojson") %>%
  st_transform('ESRI:102254') %>%
  dplyr::select(ZONEDESC, geometry) %>%
  rename(Municipality = ZONEDESC)

boulder_homes <-
  st_join(boulder_homes, munis)

boulder_homes$Municipality = ifelse(is.na(boulder_homes$Municipality),
                              "Not Incorporated", boulder_homes$Municipality)

# zip codes of Boulder County
boulder_zips <-
  st_read("https://opendata.arcgis.com/datasets/6b6091f299204e4c9c406a624baf43e6_10.geojson") %>%
  st_transform('ESRI:102254') %>%
  st_intersection(boulder_boundary, boulder_zips) %>%
  # filter only zip codes and geometry
  dplyr::select(GEOID10, geometry) %>%
  rename(ZipCode = GEOID10)

boulder_homes <-
  st_join(boulder_homes, boulder_zips)
```

```{r schools wrangling, include=TRUE, warning=FALSE, message=FALSE}

boulder_schools <-
  st_read("./colorado_schools.geojson") %>%
  st_transform('ESRI:102254') %>%
  st_intersection(boulder_boundary, boulder_schools) %>%
  filter(Type_ %in% c("Non-Public School Mailing Address",
         "Public School Physical Address"))

group_by(boulder_schools, Type_) %>%
  summarize(count = n())

st_c <- st_coordinates

boulder_homes <-
  boulder_homes %>% 
    mutate(
      schools_nn3 = nn_function(st_c(boulder_homes), st_c(boulder_schools), 3))
```


```{r school density maps, include=FALSE, warning=FALSE, message=FALSE}

boulder_private_schools <-
  boulder_schools %>%
    filter(Type_ == "Non-Public School Mailing Address") %>%
    dplyr::select(LATITUDE, LONGITUDE) %>%
    na.omit() %>%
    st_as_sf(coords = c("LONGITUDE", "LATITUDE"), crs = 4326, agr = "constant") %>%
    st_transform('ESRI:102254') %>%
    distinct()

boulder_public_schools <-
  boulder_schools %>%
    filter(Type_ == "Public School Physical Address") %>%
    dplyr::select(LATITUDE, LONGITUDE) %>%
    na.omit() %>%
    st_as_sf(coords = c("LONGITUDE", "LATITUDE"), crs = 4326, agr = "constant") %>%
    st_transform('ESRI:102254') %>%
    distinct()

ggplot() + geom_sf(data = boulder_boundary, fill = "grey40") +
  stat_density2d(data = data.frame(st_coordinates(boulder_private_schools)), 
                 aes(X, Y, fill = ..level.., alpha = ..level..),
                 size = 0.01, bins = 40, geom = 'polygon') +
  scale_fill_gradient(low = "#25CB10", high = "#FA7800", 
                      breaks=c(0.000000003,0.00000003),
                      labels=c("Minimum","Maximum"), name = "Density") +
  scale_alpha(range = c(0.00, 0.35), guide = FALSE) +
  labs(title = "Density of Private Schools, Boulder County") +
  mapTheme()

ggplot() + geom_sf(data = boulder_boundary, fill = "grey40") +
  stat_density2d(data = data.frame(st_coordinates(boulder_public_schools)), 
                 aes(X, Y, fill = ..level.., alpha = ..level..),
                 size = 0.01, bins = 40, geom = 'polygon') +
  scale_fill_gradient(low = "#25CB10", high = "#FA7800", 
                      breaks=c(0.000000003,0.00000003),
                      labels=c("Minimum","Maximum"), name = "Density") +
  scale_alpha(range = c(0.00, 0.35), guide = FALSE) +
  labs(title = "Density of Public Schools, Boulder County") +
  mapTheme()
```

```{r trailheads wrangling, include=TRUE, warning=FALSE, message=FALSE}

trailheads <-
  st_read("https://opendata.arcgis.com/datasets/3a950053bbef46c6a3c2abe3aceee3de_0.geojson") %>%
  st_transform('ESRI:102254') %>%
  st_intersection(boulder_boundary, trailheads)

boulder_homes <- boulder_homes %>% 
    mutate(
      trailheads_nn5 = nn_function(st_c(boulder_homes), st_c(trailheads), 5))
```

```{r split dataset into observed and predict, include=TRUE, warning=FALSE, message=FALSE}

boulder_homes_observed <- boulder_homes %>%
  dplyr::filter(toPredict == 0)

boulder_homes_predict <- boulder_homes %>%
  dplyr::filter(toPredict == 1)
```

```{r investigative_viz, include=FALSE, warning=FALSE, message=FALSE}

# Price per square foot
ggplot() +
  geom_sf(data = boulder_boundary, fill = NA, colour = "black") +
  geom_sf(data = boulder_homes_observed, aes(colour = q5(price_per_sf)), 
          show.legend = "point", size = .75) +
  scale_colour_manual(values = palette5,
                   labels=qBr(boulder_homes,"price_per_sf"),
                   name="Quintile\nBreaks") +
  labs(title="Price Per Square Foot, Boulder") +
  mapTheme()

#Distance from Front Range
ggplot() +
  geom_sf(data = boulder_boundary, fill = NA, colour = "black") +
  geom_sf(data = FrontRange, colour = "green") +
  geom_sf(data = boulder_homes_observed, aes(colour = q5(dist_FR)), 
          show.legend = "point", size = .75) +
  scale_colour_manual(values = palette5,
                   labels=qBr(boulder_homes,"dist_FR"),
                   name="Quintile\nBreaks") +
  labs(title="Home distance from Front Range") +
  mapTheme()

# Sale Price + zipcodes
ggplot() +
  geom_sf(data = boulder_boundary, fill = NA, colour = "black") +
  geom_sf(data = acsTractsBoulder.2019.sf, fill = NA, colour = "#55286F") +
  geom_sf(data = boulder_homes_observed, aes(colour = q5(price)), 
          show.legend = "point", size = .75) +
  scale_colour_manual(values = palette5,
                   labels=qBr(boulder_homes,"price"),
                   name="Quintile\nBreaks") +
  labs(title="Sale Price, Boulder") +
  mapTheme()

# Price vs. School Proximity
st_drop_geometry(boulder_homes_observed) %>%
  dplyr::select(price, schools_nn3) %>%
  filter(price <= 1000000) %>%
  gather(Variable, Value, -price) %>% 
   ggplot(aes(Value, price)) +
     geom_point(size = .5) + geom_smooth(method = "lm", se=F, colour = "#FA7800") +
     facet_wrap(~Variable, ncol = 3, scales = "free") +
     labs(title = "Price as a function of average distance to three nearest schools",
          x = "Average Distance to three nearest schools",
          y = "Sale Price") +
     plotTheme()

# Price vs. Trailhead Proximity
st_drop_geometry(boulder_homes_observed) %>%
  dplyr::select(price, trailheads_nn5) %>%
  filter(price <= 1000000) %>%
  gather(Variable, Value, -price) %>% 
   ggplot(aes(Value, price)) +
     geom_point(size = .5) + geom_smooth(method = "lm", se=F, colour = "#FA7800") +
     facet_wrap(~Variable, ncol = 3, scales = "free") +
     labs(title = "Price as a function of average distance to five nearest trailheads",
          x = "Average Distance to five nearest trailheads",
          y = "Sale Price") +
     plotTheme()
```

```{r build the model dataset, include=TRUE, warning=FALSE, message=FALSE}

# Select variables from boulder_homes_observed 
feature_list <-
  c("price", "med_HH_Income", "pct.over75K", "pct.Information", "pct.Finance",
    "pct.Professional","pct.Ed_Health", "nbrBedRoom", "nbrFullBaths",
    "TotalFinishedSF", "AcDscr", "Age", "schools_nn3", "trailheads_nn5", "dist_FR", 
    "qualityCodeDscr", "designCodeDscr", "ZipCode", "Municipality")

boulder.sf <- boulder_homes_observed %>% 
  select(feature_list)
```

``` {r spatial price lag, include=TRUE, warning=FALSE, message=FALSE}

coords <- st_coordinates(boulder.sf) 

neighborList <- knn2nb(knearneigh(coords, 5))

spatialWeights <- nb2listw(neighborList, style="W")

boulder.sf$lagPrice <- lag.listw(spatialWeights, boulder.sf$price)

boulder.sf %>%
  ggplot(aes(lagPrice, price)) +
     geom_point(size = .5) + geom_smooth(method = "lm", se=F, colour = "#FA7800") +
     labs(title = "Price as a function of the spatial lag of price") +
     plotTheme()
```

## Correlation Analysis

### Sale Price as a Function of Four Numerical Variables
```{r numerical variable correlation, include=TRUE, warning=FALSE, message=FALSE}

st_drop_geometry(boulder.sf) %>%
  dplyr::select(price, TotalFinishedSF, med_HH_Income, dist_FR,
                pct.over75K, schools_nn3, trailheads_nn5) %>%
  filter(price <= 4000000) %>%
  gather(Variable, Value, -price) %>% 
   ggplot(aes(Value, price)) +
     geom_point(size = .5) + geom_smooth(method = "lm", se=F, colour = "#FA7800") +
     facet_wrap(~Variable, ncol = 3, scales = "free") +
     labs(title = "Price as a function of continuous variables") +
     plotTheme()
```

### Sale Price as a Function of Three Categorical Variables
```{r categorical variable correlation, include=TRUE, warning=FALSE, message=FALSE}

# NEED TO TROUBLESHOOT
st_drop_geometry(boulder.sf) %>% 
  dplyr::select(price, AcDscr, qualityCodeDscr, designCodeDscr) %>%
  filter(price <= 4000000) %>%
  gather(Variable, Value, -price) %>% 
   ggplot(aes(Value, price)) +
     geom_bar(position = "dodge", stat = "summary", fun.y = "mean") +
     facet_wrap(~Variable, ncol = 1, scales = "free") +
     labs(title = "Price as a function of\ncategorical variables", y = "Mean_Price") +
     plotTheme() + theme(axis.text.x = element_text(angle = 45, hjust = 1))
```

### Correlation Matrix
``` {r correlation matrix, include=TRUE, warning=FALSE, message=FALSE}

numericVars <- 
  select_if(st_drop_geometry(boulder.sf), is.numeric) %>% na.omit()

ggcorrplot(
  round(cor(numericVars), 1), 
  p.mat = cor_pmat(numericVars),
  colors = c("#25CB10", "white", "#FA7800"),
  type="lower",
  insig = "blank") +   
    labs(title = "Correlation across numeric variables")
```

## OLS Regression

```{r regression 1, include=TRUE, message=FALSE, warning=FALSE, echo=TRUE}
# add ZipCode to reg1
reg1 <- lm(price ~ ., data = st_drop_geometry(boulder.sf) %>%
             dplyr::select("price", "med_HH_Income", "pct.over75K", "pct.Information",
                           "pct.Finance", "pct.Professional","pct.Ed_Health",
                           "nbrBedRoom", "nbrFullBaths","TotalFinishedSF", "AcDscr",
                           "Age", "schools_nn3", "trailheads_nn5", "dist_FR", 
                           "qualityCodeDscr", "designCodeDscr", "ZipCode"))
summary(reg1)
```

```{r predictions, include=TRUE, message=FALSE, warning=FALSE, echo=TRUE}

boulder_homes_predict$price <-
  predict.lm(reg1, boulder_homes_predict)

boulder_homes_predict_condensed <-
  subset(boulder_homes_predict, select=c("price", "MUSA_ID")) %>%
  st_drop_geometry()

write.csv(boulder_homes_predict_condensed, "./The_Simon_&_Garfunkel_Tribute_Band.csv")

```

```{r PartionData, include=TRUE, warning=FALSE, message=FALSE}

inTrain <- createDataPartition(y = paste(boulder.sf$qualityCodeDscr, boulder.sf$designCodeDscr, boulder.sf$Municipality, boulder.sf$AcDscr),
                               p = 0.75, list = FALSE)

boulder.training <- boulder.sf[inTrain,]
boulder.test <- boulder.sf[-inTrain,]

reg.training <- lm(price ~ ., data = as.data.frame(boulder.training) %>%       
                  dplyr::select("price", "med_HH_Income", "pct.over75K", 
                                "pct.Information", "pct.Finance", "pct.Professional",
                                "pct.Ed_Health","nbrBedRoom", "nbrFullBaths",
                                "TotalFinishedSF", "AcDscr", "Age", "schools_nn3",
                                "trailheads_nn5", "dist_FR", "qualityCodeDscr",
                                "designCodeDscr"))
```

```{r predict on test set, include=TRUE, warning=FALSE, message=FALSE}

boulder.test <-
  boulder.test %>%
  mutate(Regression = "Baseline Regression",
         price.predict = predict(reg.training, boulder.test),
         price.error = price.predict - price,
         price.abserror = abs(price.predict - price),
         price.ape = (abs(price.predict - price)) / price.predict)%>%
  filter(price < 5000000)
```

``` {r summary statistics, include=TRUE, warning=FALSE, message=FALSE}

mean(boulder.sf$price, na.rm = T)
mean(boulder.test$price.abserror, na.rm = T)
mean(boulder.test$price.ape, na.rm = T)
```

```{r ACCURACY//visualize, include=TRUE, warning=FALSE, message=FALSE}

# histogram of absolute errors

ggplot(boulder.test, aes(x = price.abserror)) +
  geom_histogram(binwidth=10000, fill = "green", colour = "white") +
  scale_x_continuous(limits = c(0, 1000000)) +
  labs(title = "Distribution of prediction errors",
       x = "Sale Price Absolute Error", y = "Count") +
  plotTheme()

ggplot(boulder.test) +
  geom_point(aes(price.predict, price)) +
  geom_smooth(aes(price, price), colour = "orange") +
  geom_smooth(method = "lm", aes(price.predict, price), se = FALSE, colour = "green") +
  labs(title = "Predicted sale price as a function of observed price",
       x = "Predicted Sale Price", y = "Observed Sale Price") +
  plotTheme()
```

```{r cross validation, include=TRUE, warning=FALSE, message=FALSE}

fitControl <- trainControl(method = "cv", number = 100)
set.seed(825)

reg.cv <- 
  train(price ~ ., data = st_drop_geometry(boulder.sf), 
     method = "lm", trControl = fitControl, na.action = na.pass)

reg.cv
```

```{r exploring cross validation results, include=TRUE, warning=FALSE, message=FALSE}

mean(reg.cv$resample[,3])
sd(reg.cv$resample[,3])

mae <- data.frame(reg.cv$resample[,3]) %>%
  rename(mae = reg.cv.resample...3.)

# histogram of cross validation MAE
ggplot(mae, aes(x = mae)) +
  geom_histogram(binwidth=10000, fill = "orange", colour = "white") +
  scale_x_continuous(labels = c(0, 100000, 200000, 300000, 400000, 500000), 
                     limits = c(0, 500000)) +
  labs(title = "Distribution of MAE",
       subtitle = "k-fold cross validation; k = 100",
       x = "Mean Absolute Error", y = "Count") +
  plotTheme()
```


``` {r spatial error lag, include=TRUE, warning=FALSE, message=FALSE}

coords.test <- st_coordinates(boulder.test) 

neighborList.test <- knn2nb(knearneigh(coords.test, 5))

spatialWeights.test <- nb2listw(neighborList.test, style="W")

boulder.test %>%
  mutate(lagPriceError = lag.listw(spatialWeights.test, price.error)) %>%
  ggplot(aes(lagPriceError, price.error)) +
     geom_point(size = .5) + geom_smooth(method = "lm", se=F, colour = "#FA7800") +
     labs(title = "Error as a function of the spatial lag of price") +
     plotTheme()
```

``` {r moran's i, include=TRUE, warning=FALSE, message=FALSE}

moranTest <- moran.mc(boulder.test$price.error,
                      spatialWeights.test, nsim = 999)

ggplot(as.data.frame(moranTest$res[c(1:999)]), aes(moranTest$res[c(1:999)])) +
  geom_histogram(binwidth = 0.01) +
  geom_vline(aes(xintercept = moranTest$statistic), colour = "#FA7800",size=1) +
  scale_x_continuous(limits = c(-1, 1)) +
  labs(title="Observed and permuted Moran's I",
       subtitle= "Observed Moran's I in orange",
       x="Moran's I",
       y="Count") +
  plotTheme()
```

## Accounting For Neighborhood

```{r accounting for spatial autocorrelation, include=TRUE, warning=FALSE, message=FALSE}
left_join(
  st_drop_geometry(boulder.test) %>%
    group_by(ZipCode) %>%
    summarize(meanPrice = mean(price, na.rm = T)),
  mutate(boulder.test, predict.fe = 
                        predict(lm(price ~ ZipCode, data = boulder.test), 
                        boulder.test)) %>%
    st_drop_geometry %>%
    group_by(ZipCode) %>%
      summarize(meanPrediction = mean(predict.fe))) %>%
      kable() %>% kable_styling()

# new regression accounting for areal (municipality/zip code/census tract) effects

reg.nhood <- lm(price ~ ., data = as.data.frame(boulder.training) %>%       
                  dplyr::select("price", "med_HH_Income", "pct.over75K", 
                                "pct.Information", "pct.Finance", "pct.Professional",
                                "pct.Ed_Health","nbrBedRoom", "nbrFullBaths",
                                "TotalFinishedSF", "AcDscr", "Age", "schools_nn3",
                                "trailheads_nn5", "dist_FR", "qualityCodeDscr",
                                "designCodeDscr", "Municipality"))
summary(reg.nhood)

boulder.test.nhood <-
  boulder.test %>%
  mutate(Regression = "Neighborhood Effects",
         price.predict = predict(reg.nhood, boulder.test),
         price.error = price.predict- price,
         price.abserror = abs(price.predict- price),
         price.ape = (abs(price.predict- price)) / price)%>%
  filter(price < 5000000)

# Bring both regressions into one data frame

bothRegressions <- 
  rbind(
    dplyr::select(boulder.test, starts_with("price"), Regression, ZipCode) %>%
      mutate(lagPriceError = lag.listw(spatialWeights.test, price.error)),
    dplyr::select(boulder.test.nhood, starts_with("price"), Regression, ZipCode) %>%
      mutate(lagPriceError = lag.listw(spatialWeights.test, price.error)))

st_drop_geometry(bothRegressions) %>%
  gather(Variable, Value, -Regression, -ZipCode) %>%
  filter(Variable == "price.abserror" | Variable == "price.ape") %>%
  group_by(Regression, Variable) %>%
    summarize(meanValue = mean(Value, na.rm = T)) %>%
    spread(Variable, meanValue) %>%
    kable()

bothRegressions %>%
  dplyr::select(price.predict, price, Regression) %>%
    ggplot(aes(price, price.predict)) +
  geom_point() +
  stat_smooth(aes(price, price), 
             method = "lm", se = FALSE, size = 1, colour="#FA7800") + 
  stat_smooth(aes(price.predict, price), 
              method = "lm", se = FALSE, size = 1, colour="#25CB10") +
  facet_wrap(~Regression) +
  labs(title="Predicted sale price as a function of observed price",
       subtitle="Orange line represents a perfect prediction; Green line represents prediction") +
  plotTheme()

# for generalizability, use reg1
```